### ISSUE TITLE
Day length seems wrong?

### ISSUE THREAD

**Issue by zeroinformatique** [stevehead/ksp-SimpleOrbitCalculator#11]
Kerbin's day is 6 hours, but I have the feeling you use 24h in SOC which gives wrong results.

**Comment by stevehead** [comment]
The plugin is a calculator using real world physics and SI units or SI derived units. The 6-hour day of Kerbin is more of a calendar feature similar to martian time on Mars; it should never be used in calculations of orbit and physical characteristics. Using 24-hour time exclusively also ensures no confusion for those that have solar system modifications from Kopernicus, such as 64k or RSS, which this plugin was originally designed for. This is personal opinion, but I recommend to change the settings in the stock game to use real 24-hour time as there is no justification to use the default 6-hour day length.
